[template]

[hooks]
pre = ["init.rhai", "../common.rhai", "vars.rhai"]
post = ["conditional-files.rhai"]

[placeholders]
is_fullstack = { prompt = "Do you want to use Dioxus Fullstack?", default = true, type = "bool" }
is_router = { prompt = "Do you want to use the Dioxus Router?", default = true, type = "bool" }
